title: "[Submit site] "
labels: ["Showcase"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for sharing your website with the Hyas community!
        
        What we look for when reviewing submissions to the [Showcase](https://gethyas.com/showcase/):

        - Your website is built with Hyas.
        - Your website is public.
        - Your website is an example.
  - type: input
    id: name
    attributes:
      label: Name
      description: Your website's name.
      placeholder: My super cool site
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: URL
      description: Your website's URL.
      placeholder: 'https://example.com/'
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what your site is about.
    validations:
      required: false
  - type: textarea
    id: why
    attributes:
      label: Why?
      description: A clear and concise description of why you think your site should be added to the showcase.
      placeholder: This is what makes my website an example.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      options:
        - label:  I agree to the [Terms of Service](https://gethyas.com/terms/).
          required: true
